library(data.table)
df <- fread("household_power_consumption.txt", sep=";")
dfa <- df[grep("[12]/2/2007",df$Date)]
a <- paste(dfa$Date,dfa$Time,sep=" ")
b <- strptime(a,"%d/%m/%Y %H:%M:%S")
t1 <- strptime("1/2/2007 00:00:00","%d/%m/%Y %H:%M:%S")
t2 <- strptime("2/2/2007 23:59:59","%d/%m/%Y %H:%M:%S")
d <- (t1<=b & b <=t2)
dfs<-dfa[d]
x <- strptime(paste(dfs$Date,dfs$Time,sep=" "),"%d/%m/%Y %H:%M:%S")
sm1 <- as.numeric(dfs$Sub_metering_1)
sm2 <- as.numeric(dfs$Sub_metering_2)
sm3 <- as.numeric(dfs$Sub_metering_3)

plot(x, sm1, type="l",col="black",ylab = "Energy Sub metering",xlab = NA)
lines(x,sm2,col="red")
lines(x,sm3,col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty = 1,cex=0.5)
dev.copy(png,file="plot3.png")
dev.off()